# frozen_string_literal: true

# source 'https://rubygems.org'

gem 'fluent-plugin-detect-exceptions', '~>0.0.9'
gem 'fluent-plugin-elasticsearch', '~>2.8.5'
gem 'fluent-plugin-grep'
gem 'fluent-plugin-grok-parser'
gem 'fluent-plugin-multi-format-parser', '~>1.0.0'
gem 'fluent-plugin-parser'
gem 'fluent-plugin-rewrite-tag-filter'
# gem 'fluent-plugin-systemd', '~>0.3.1'
